[input]
base_directory = "transcripts/autumn-in-hieron"
url_prefix = "https://docs.google.com/document/d/"
stemming = "None"
[[input.files]]
path = "19odgykm_oADvQNZAkwdWBCOsAVPpjAlRq9qt8ElrGN8.txt"
url = "19odgykm_oADvQNZAkwdWBCOsAVPpjAlRq9qt8ElrGN8"
title = "An Introduction to Friends at the Table"

[[input.files]]
path = "1xCBFsZqxr56ELVzXcpZ5nmH8bQO-rUHE66dbUEWgnA4.txt"
url = "1xCBFsZqxr56ELVzXcpZ5nmH8bQO-rUHE66dbUEWgnA4"
title = "Autumn in Hieron 00: We’re Not Calling It Duckberg"

[[input.files]]
path = "1sGQ3G9hATV_mBzrWLKPzFX2sZgdrGwIrleNBmUoC2O8.txt"
url = "1sGQ3G9hATV_mBzrWLKPzFX2sZgdrGwIrleNBmUoC2O8"
title = "Autumn in Hieron 01: We Have Not Yet Begun To Be Pompous"

[[input.files]]
path = "1tKREOydDofdyNWsEiAYGa6Oe4rdgIXvbq57f-BQoJtk.txt"
url = "1tKREOydDofdyNWsEiAYGa6Oe4rdgIXvbq57f-BQoJtk"
title = "Autumn in Hieron 02: You Found Out What Was Magical"

[[input.files]]
path = "1_Lbd0qtfApJPfYVWj9e9mtn1yRUbOwrkyspZi-49MPM.txt"
url = "1_Lbd0qtfApJPfYVWj9e9mtn1yRUbOwrkyspZi-49MPM"
title = "Autumn in Hieron 03: A Podcast About Listening"

[[input.files]]
path = "1bQBl-pe7V3KXu_oY4FKJatFGEuKqjHzbzGBPkAewd2c.txt"
url = "1bQBl-pe7V3KXu_oY4FKJatFGEuKqjHzbzGBPkAewd2c"
title = "Autumn in Hieron 04: Is It Time Already?"

[[input.files]]
path = "1XdbXmjv2injl8Ua7_KtpaBRzIvCsv23w269KvvV4rJs.txt"
url = "1XdbXmjv2injl8Ua7_KtpaBRzIvCsv23w269KvvV4rJs"
title = "Autumn in Hieron 05: What’s a Good Name For A Ship?"

[[input.files]]
path = "112IWBUU1Yes1A7u75xKSxvGjFtcktUzW0weW0uLPvN4.txt"
url = "112IWBUU1Yes1A7u75xKSxvGjFtcktUzW0weW0uLPvN4"
title = "Autumn in Hieron 06: A Bad Trip"

[[input.files]]
path = "1Sw-f33rrfarmd1AX8Gmd8bENbnmdItVBCTKIqimV_Uk.txt"
url = "1Sw-f33rrfarmd1AX8Gmd8bENbnmdItVBCTKIqimV_Uk"
title = "Autumn in Hieron 07: Boat Party?"

[[input.files]]
path = "1Qe-Za5Yq_60X2-xIINdzP3EAVXxicwAR4zzK991YhgQ.txt"
url = "1Qe-Za5Yq_60X2-xIINdzP3EAVXxicwAR4zzK991YhgQ"
title = "Autumn in Hieron 08: On The Tip Of Your Tongue"

[[input.files]]
path = "1znte6qTjshc1vFiF7UE9H3tk1FwEcTjBsLuWWWkL0yU.txt"
url = "1znte6qTjshc1vFiF7UE9H3tk1FwEcTjBsLuWWWkL0yU"
title = "Autumn in Hieron 09: I’m Not Happy With This Decision At All"

[[input.files]]
path = "1B59UxpObG0U_ky8o5YbyRC4RC2xS-a9hbzJBB-DT_Kk.txt"
url = "1B59UxpObG0U_ky8o5YbyRC4RC2xS-a9hbzJBB-DT_Kk"
title = "Autumn in Hieron 10: Chekhov’s Torture Elf"

[[input.files]]
path = "1BHXPnZty5CHuZAQwiB2019m_doof7ADB3wksa_NWzNo.txt"
url = "1BHXPnZty5CHuZAQwiB2019m_doof7ADB3wksa_NWzNo"
title = "Autumn in Hieron 11: Like Sneaky Little Sneaks"

[[input.files]]
path = "1OSPBC5R-8M0KoAmJfjEQS86wqdxCWQWCSGRlLklbjQI.txt"
url = "1OSPBC5R-8M0KoAmJfjEQS86wqdxCWQWCSGRlLklbjQI"
title = "Autumn in Hieron 12: Knowledge and Ignorance"

[[input.files]]
path = "1IpnFHplPXGH2IOEpTs9g2w-yLGTEkpH2VQuawpUUK4o.txt"
url = "1IpnFHplPXGH2IOEpTs9g2w-yLGTEkpH2VQuawpUUK4o"
title = "Autumn in Hieron 13: What A Surprise"

[[input.files]]
path = "1Kz3rzwRRpSdMoIkXAIWI3hmdgOuiwUql5U_ZlBka2tE.txt"
url = "1Kz3rzwRRpSdMoIkXAIWI3hmdgOuiwUql5U_ZlBka2tE"
title = "Autumn in Hieron: Holiday Special 01: I Don’t Know What’s in That Box"

[[input.files]]
path = "1B_GSuQ42l0Y2kcxiGl0gC1cgcKekDmV4DbmGsaQOV0w.txt"
url = "1B_GSuQ42l0Y2kcxiGl0gC1cgcKekDmV4DbmGsaQOV0w"
title = "Autumn in Hieron: Holiday Special 02: I’ve Killed Monsters"

[[input.files]]
path = "1xyHZAhhv1uaJONTXVs9r9sWvYNCCCxWv6y31zMax0wY.txt"
url = "1xyHZAhhv1uaJONTXVs9r9sWvYNCCCxWv6y31zMax0wY"
title = "Autumn in Hieron 14: A Fire Hydrant of Divinity"

[[input.files]]
path = "1Zxf5R4YiPCyHkGneCSxnTA402GfJBfEM6I9_S3RFDD0.txt"
url = "1Zxf5R4YiPCyHkGneCSxnTA402GfJBfEM6I9_S3RFDD0"
title = "Autumn in Hieron 15: Have You Ever Swung A Sword At A Ghost Before?"

[[input.files]]
path = "1cnLCI-g5NAqt6Dd-IaHcNOraiKRujeZvOJY9GRqpKVI.txt"
url = "1cnLCI-g5NAqt6Dd-IaHcNOraiKRujeZvOJY9GRqpKVI"
title = "Autumn in Hieron 16: Those Woods You Chose"

[[input.files]]
path = "1vptygnyKDEPUnICnnpCTpYOpZxfbPebn-st23oZ2Yro.txt"
url = "1vptygnyKDEPUnICnnpCTpYOpZxfbPebn-st23oZ2Yro"
title = "Autumn in Hieron 17: As Death’s Eyes Look Over The World"

[[input.files]]
path = "1WqnCE4BlWsiWBXR4z9SX6B7Q_StMaXbh6dAlPYPqdRg.txt"
url = "1WqnCE4BlWsiWBXR4z9SX6B7Q_StMaXbh6dAlPYPqdRg"
title = "Autumn in Hieron 18: Magic (Or Something) Is All Around Us"

[[input.files]]
path = "10fwGxLGO0KBnB9b5p0nyqvp2YB4csJB7JFNltMOoQj0.txt"
url = "10fwGxLGO0KBnB9b5p0nyqvp2YB4csJB7JFNltMOoQj0"
title = "Autumn in Hieron 19: Violence Mulligan Mulligan"

[[input.files]]
path = "1uEEyEY0CcWKuo0pWSSXcRpbJUyO4haeiate3zYdeW4Y.txt"
url = "1uEEyEY0CcWKuo0pWSSXcRpbJUyO4haeiate3zYdeW4Y"
title = "Autumn in Hieron 20: Do I Feel Followed?"

[[input.files]]
path = "1Q0-VP3_DdZzQ7xE9LmyK5kLi1Vqy6MTLOerdWtGwzxM.txt"
url = "1Q0-VP3_DdZzQ7xE9LmyK5kLi1Vqy6MTLOerdWtGwzxM"
title = "Autumn in Hieron 21: The Storm Over Tristero"

[[input.files]]
path = "1F0BUHPkeX1ShpOWzxl_xr2BqbjlD4xsmHDwZLRQ_i1w.txt"
url = "1F0BUHPkeX1ShpOWzxl_xr2BqbjlD4xsmHDwZLRQ_i1w"
title = "Autumn in Hieron 22: Closing the Window"

[[input.files]]
path = "1xk-tRqgsn65kTy6gNplng6qYJKgNuGuLZ4BAP41c-1k.txt"
url = "1xk-tRqgsn65kTy6gNplng6qYJKgNuGuLZ4BAP41c-1k"
title = "Autumn in Hieron 23: Spinning Straw Out Of Gold"

[[input.files]]
path = "1ND8ah8CTIopM97F7UsMukMD_fMdtdEuBFFCM0rL6L4s.txt"
url = "1ND8ah8CTIopM97F7UsMukMD_fMdtdEuBFFCM0rL6L4s"
title = "Autumn in Hieron 24: A Paladin is a Tool"

[[input.files]]
path = "1HFKCMM7f74dP30FNbzBq0ZkrvX2A7cLxYwLFmXNGeDE.txt"
url = "1HFKCMM7f74dP30FNbzBq0ZkrvX2A7cLxYwLFmXNGeDE"
title = "Autumn in Hieron 25: Work Off Your Sins"

[[input.files]]
path = "1TTy0x1iYdvYoeaolRe1a_yMqxUfO7PCt9yxC925p8TE.txt"
url = "1TTy0x1iYdvYoeaolRe1a_yMqxUfO7PCt9yxC925p8TE"
title = "Autumn in Hieron 26: Why Are You Here, Again?"

[[input.files]]
path = "1N77h8Sd1wE5ZNjVxsBlE11AcqWGuaKsh_V0MxDfmqKk.txt"
url = "1N77h8Sd1wE5ZNjVxsBlE11AcqWGuaKsh_V0MxDfmqKk"
title = "Autumn in Hieron 27: The Shores of Ordenna"

[[input.files]]
path = "1neSxYVTSu6T07ZtaGkoJXgBc8qCnd3XLThkuWopwehk.txt"
url = "1neSxYVTSu6T07ZtaGkoJXgBc8qCnd3XLThkuWopwehk"
title = "Autumn in Hieron 28: A Choice About What You Believe"

[[input.files]]
path = "1Nb73-BDfUzxYbNIDiVKGe6W-GvZNxFCfI7jHDNGtJbk.txt"
url = "1Nb73-BDfUzxYbNIDiVKGe6W-GvZNxFCfI7jHDNGtJbk"
title = "Autumn in Hieron 29: Live Post Mortem"

