[input]
base_directory = "transcripts/counter-weight"
url_prefix = "https://docs.google.com/document/d/"
stemming = "None"
[[input.files]]
path = "1zGovC79LsvuwVViOvqTCtz3SbRGHfZETRwkFm1WFFqg.txt"
url = "1zGovC79LsvuwVViOvqTCtz3SbRGHfZETRwkFm1WFFqg"
title = "COUNTER/Weight -01: Secret World Gen Episode"

[[input.files]]
path = "1dhlsagqfVSudwUyokFRNvQWHkUOJIUC2D4sXBNDCNSI.txt"
url = "1dhlsagqfVSudwUyokFRNvQWHkUOJIUC2D4sXBNDCNSI"
title = "COUNTER/Weight 00: If Han Solo Used To Be Beyoncé, or: Hashtag Otechku"

[[input.files]]
path = "1mh8uLkw9dOkfiiMTvMUOilV-1Q9cC5OofAp_galM_RE.txt"
url = "1mh8uLkw9dOkfiiMTvMUOilV-1Q9cC5OofAp_galM_RE"
title = "COUNTER/Weight 01: I Would Like A Bribe"

[[input.files]]
path = "12ZzLK1LcKfgRwGVM83hujIXtpGFqhjhYIqOyZiVESDk.txt"
url = "12ZzLK1LcKfgRwGVM83hujIXtpGFqhjhYIqOyZiVESDk"
title = "COUNTER/Weight 02: Soldier Game"

[[input.files]]
path = "1RAHszTNZAxrr5mHH7rsZ-8ZcmwZYLOOTpEi9eWbdz0g.txt"
url = "1RAHszTNZAxrr5mHH7rsZ-8ZcmwZYLOOTpEi9eWbdz0g"
title = "COUNTER/Weight 03: It’s Fine, We’re Criminals"

[[input.files]]
path = "1frsrs_DN4bQ8a6r3ew4EjyVELCKCYTPnxPlcKHc0acU.txt"
url = "1frsrs_DN4bQ8a6r3ew4EjyVELCKCYTPnxPlcKHc0acU"
title = "COUNTER/Weight 04: The Bells Are Ringing"

[[input.files]]
path = "19CSVitxMRtKKXr8m4swuczgAHtwcTT6sEEZaxSzQpgI.txt"
url = "19CSVitxMRtKKXr8m4swuczgAHtwcTT6sEEZaxSzQpgI"
title = "COUNTER/Weight 06: Here’s Your Bribe Tip"

[[input.files]]
path = "1lhNyIPWe3YfGL_YYdcHB6ezKj9tL7uoW4-2njNAdPYc.txt"
url = "1lhNyIPWe3YfGL_YYdcHB6ezKj9tL7uoW4-2njNAdPYc"
title = "COUNTER/Weight 07: I Am Not Allowed"

[[input.files]]
path = "1nw1FxaxTJ40a8hqqU-nTy_auC3zehaVjvCWvAh4AwYg.txt"
url = "1nw1FxaxTJ40a8hqqU-nTy_auC3zehaVjvCWvAh4AwYg"
title = "COUNTER/Weight 08: Our Hostage Below"

[[input.files]]
path = "1cBdGrMwA4DdcoAgwDYb75Qmdgz4XZwKQBLD9YW4Ni1k.txt"
url = "1cBdGrMwA4DdcoAgwDYb75Qmdgz4XZwKQBLD9YW4Ni1k"
title = "COUNTER/Weight 09: This Month Of Ours"

[[input.files]]
path = "1wtmzUIBlFn5oKtAQcnaBNgrHOSEuu9i64L4-C5Wj2yk.txt"
url = "1wtmzUIBlFn5oKtAQcnaBNgrHOSEuu9i64L4-C5Wj2yk"
title = "COUNTER/Weight 10: Drawing Clocks"

[[input.files]]
path = "1_zHGRtTLKXahrdEIlcCEFGddIEkrWp0LcGIRvV5yFDw.txt"
url = "1_zHGRtTLKXahrdEIlcCEFGddIEkrWp0LcGIRvV5yFDw"
title = "COUNTER/Weight 11: A Thing You Know About Nightclubs"

[[input.files]]
path = "1Kxs2MC2ygjiOKTGx-BKYH3ykFxxXWOyzSXTnkhnYudo.txt"
url = "1Kxs2MC2ygjiOKTGx-BKYH3ykFxxXWOyzSXTnkhnYudo"
title = "COUNTER/Weight 12: A Home After A Wake"

[[input.files]]
path = "1axrkgj-V9GA-2kpKrGAm8kcHP5YZCOFX8WiCY_IBzss.txt"
url = "1axrkgj-V9GA-2kpKrGAm8kcHP5YZCOFX8WiCY_IBzss"
title = "COUNTER/Weight 13: Our Customer of the Month"

[[input.files]]
path = "174wMIQjE6vkDy6y8zieQdfuUBajluVBh3LNdFga2QvQ.txt"
url = "174wMIQjE6vkDy6y8zieQdfuUBajluVBh3LNdFga2QvQ"
title = "COUNTER/Weight 14: We’ve All Killed People"

[[input.files]]
path = "1MPTGfKDr1rGpimeYBcNv7WRp2h9AvqWYbZRxlsL0r2Y.txt"
url = "1MPTGfKDr1rGpimeYBcNv7WRp2h9AvqWYbZRxlsL0r2Y"
title = "COUNTER/Weight 15: A Candle in the Sun"

[[input.files]]
path = "1qxHa2TFjR_xZkANDVNwXsDXwpXzsIOqtNt6lWiwWqH8.txt"
url = "1qxHa2TFjR_xZkANDVNwXsDXwpXzsIOqtNt6lWiwWqH8"
title = "COUNTER/Weight 16: The Rear Left Engine"

[[input.files]]
path = "1yzOKk9rbScejA1Pb2Zju0JpHSAL8RmbWStB4bs3LFxg.txt"
url = "1yzOKk9rbScejA1Pb2Zju0JpHSAL8RmbWStB4bs3LFxg"
title = "COUNTER/Weight 17: Metal That Has Died Twice"

[[input.files]]
path = "18BBHEX5HhxxlwT-QZ_gvkcYIKHyqo7TbgyeJqkWRP7k.txt"
url = "18BBHEX5HhxxlwT-QZ_gvkcYIKHyqo7TbgyeJqkWRP7k"
title = "COUNTER/Weight 18: The Order of Things"

[[input.files]]
path = "1wwdORMRDDGNvA_xUfMZ5IMGJsS_sGeoLYPf8ggfYb3s.txt"
url = "1wwdORMRDDGNvA_xUfMZ5IMGJsS_sGeoLYPf8ggfYb3s"
title = "COUNTER/Weight 19: The Road You Take And Who You Take It With"

[[input.files]]
path = "1Cur7KA7HA57LY58mcZYNmFc4wUU2U8OrM8jnLKJJzXQ.txt"
url = "1Cur7KA7HA57LY58mcZYNmFc4wUU2U8OrM8jnLKJJzXQ"
title = "COUNTER/Weight 20: The Glimmer Incident: The Executive Enters!"

[[input.files]]
path = "1tvjEiwmI2thMAtfiBIQ3KYydJU4wyVUc9eUxSXhTTqo.txt"
url = "1tvjEiwmI2thMAtfiBIQ3KYydJU4wyVUc9eUxSXhTTqo"
title = "COUNTER/Weight 21: Crisis! (A Solemn Vow Above The Sea of Counterweight)"

[[input.files]]
path = "1IgqusuLppdv7YWl4VOHCq3a0IW8ePEu5EGzbS133Zhs.txt"
url = "1IgqusuLppdv7YWl4VOHCq3a0IW8ePEu5EGzbS133Zhs"
title = "COUNTER/Weight 22: The Broken Branch"

[[input.files]]
path = "1xYk9E3HNzL3YhuXxojsPMw5Or8ReDrSsDw-5mq4mltw.txt"
url = "1xYk9E3HNzL3YhuXxojsPMw5Or8ReDrSsDw-5mq4mltw"
title = "COUNTER/Weight 23: An Astonishingly Illegal Ship"

[[input.files]]
path = "1Rhs25IuZM9WQkNmkQrzkpVBLQ9dR9Zq4TIwvjwBCNpw.txt"
url = "1Rhs25IuZM9WQkNmkQrzkpVBLQ9dR9Zq4TIwvjwBCNpw"
title = "COUNTER/Weight 24: It’s Still Dark Out"

[[input.files]]
path = "1TLQf8wVYi8brq5wvzaHfAzp3crTyFA5SjW6FHwMX18M.txt"
url = "1TLQf8wVYi8brq5wvzaHfAzp3crTyFA5SjW6FHwMX18M"
title = "COUNTER/Weight 25: You Can Call Me Captain"

[[input.files]]
path = "1X3F4zcYL_loYDu5vLFdZbdg70uX-tgc3YAcjvzv7-r4.txt"
url = "1X3F4zcYL_loYDu5vLFdZbdg70uX-tgc3YAcjvzv7-r4"
title = "COUNTER/Weight 26: Do You Have Room For Me?"

[[input.files]]
path = "1uftSYbIlWsmwNLGZSrspcpV48jrPemjveGJrkFMw_TI.txt"
url = "1uftSYbIlWsmwNLGZSrspcpV48jrPemjveGJrkFMw_TI"
title = "COUNTER/Weight 27: An Animal Out of Context"

[[input.files]]
path = "14vys-zQqtpjrrmgXPufHtknmqGM-ejM59eoEsA_vN0k.txt"
url = "14vys-zQqtpjrrmgXPufHtknmqGM-ejM59eoEsA_vN0k"
title = "COUNTER/Weight 28: A Special Kind of Warmth"

[[input.files]]
path = "1-MGS6XXccDo05z_iwEFXlma--RRoouIQiZ8JoysWokU.txt"
url = "1-MGS6XXccDo05z_iwEFXlma--RRoouIQiZ8JoysWokU"
title = "COUNTER/Weight 29: Three Conversations"

[[input.files]]
path = "16SlanKUNyiVILsuNb9AuFweXTiehrz4wIH-JPNrirOQ.txt"
url = "16SlanKUNyiVILsuNb9AuFweXTiehrz4wIH-JPNrirOQ"
title = "COUNTER/Weight 30: Another Facility Among Trees"

[[input.files]]
path = "1G3esJnyHRLwCPO7ZLAR2DHR5LzTRN5YU-R_fL0dml3c.txt"
url = "1G3esJnyHRLwCPO7ZLAR2DHR5LzTRN5YU-R_fL0dml3c"
title = "COUNTER/Weight 31: Expertize with a Z"

[[input.files]]
path = "1jAkxN2wUXP2O50bvXo3nhA_aBhiwVMXn49T9LwouFjQ.txt"
url = "1jAkxN2wUXP2O50bvXo3nhA_aBhiwVMXn49T9LwouFjQ"
title = "COUNTER/Weight 32: Through The Crosshairs"

[[input.files]]
path = "1ZZ6l8epOeigeGnNw_ORFEOrZb-GFHFjqWLA54CXqazU.txt"
url = "1ZZ6l8epOeigeGnNw_ORFEOrZb-GFHFjqWLA54CXqazU"
title = "COUNTER/Weight 33: A Fractal Garden and an Intercepted Message"

[[input.files]]
path = "1wkGPXdSbyXVL5syIKq9NjnQ6secDbiskzmh8lMHv4QY.txt"
url = "1wkGPXdSbyXVL5syIKq9NjnQ6secDbiskzmh8lMHv4QY"
title = "COUNTER/Weight 34: Reaching Out"

[[input.files]]
path = "1azQF-B4O-hHvzpp-6_QE-8UuTRuOlGbIP8dz5p3Bwyg.txt"
url = "1azQF-B4O-hHvzpp-6_QE-8UuTRuOlGbIP8dz5p3Bwyg"
title = "COUNTER/Weight 35: A Knock at the Door"

[[input.files]]
path = "1iyZCsvyeefkjY6rsnx5oYQhpk3DZ44iuUq7ct3JC6J0.txt"
url = "1iyZCsvyeefkjY6rsnx5oYQhpk3DZ44iuUq7ct3JC6J0"
title = "COUNTER/Weight 36: Everything is Temporary"

[[input.files]]
path = "1ZIhr8_alkz_SfmHovIVWt1e3Izqf5UOfikjCFkN-UC0.txt"
url = "1ZIhr8_alkz_SfmHovIVWt1e3Izqf5UOfikjCFkN-UC0"
title = "COUNTER/Weight 37: Visions from Windows, Or: The Last Time the Bomb Dropped"

[[input.files]]
path = "1FDXf11B7W3wigDZeYgxpXR_-N1elCAdqt3K26n0Y3D4.txt"
url = "1FDXf11B7W3wigDZeYgxpXR_-N1elCAdqt3K26n0Y3D4"
title = "COUNTER/Weight 38: Found Footage"

[[input.files]]
path = "159OscYtwecH661AxBD6kpERKJgyqFio1rUlJCrDBmH0.txt"
url = "159OscYtwecH661AxBD6kpERKJgyqFio1rUlJCrDBmH0"
title = "COUNTER/Weight 39: Just Another Machine"

[[input.files]]
path = "1BiqYG9bkyaM5aVdBoE6VupR8rq0hkxUAjq9-VUWiGFc.txt"
url = "1BiqYG9bkyaM5aVdBoE6VupR8rq0hkxUAjq9-VUWiGFc"
title = "COUNTER/Weight 40: The Storm Over September"

[[input.files]]
path = "1Ij9K7s54RnIy7H2NSzb2RSUAvo6VWYTLUfiiWFgHYfE.txt"
url = "1Ij9K7s54RnIy7H2NSzb2RSUAvo6VWYTLUfiiWFgHYfE"
title = "COUNTER/Weight 41: A Splintered Branch, A Ringing Bell Pt. 1"

[[input.files]]
path = "1fe1wP5Ik-Ds9tdnhrFC7J8SgBHIlQFPwmkN0jrc2Z1g.txt"
url = "1fe1wP5Ik-Ds9tdnhrFC7J8SgBHIlQFPwmkN0jrc2Z1g"
title = "COUNTER/Weight 42: A Splintered Branch, A Ringing Bell Pt. 2"

[[input.files]]
path = "1R6BoFUKEYVF_zqOa06TNoSKOLuTAOASCP-9yVv1kT5I.txt"
url = "1R6BoFUKEYVF_zqOa06TNoSKOLuTAOASCP-9yVv1kT5I"
title = "COUNTER/Weight 43: A Splintered Branch, A Ringing Bell Pt. 3"

[[input.files]]
path = "1jM31VkB31Fw84t0LcfQtwSr_FmFFGhPYlisZ7tYm2NM.txt"
url = "1jM31VkB31Fw84t0LcfQtwSr_FmFFGhPYlisZ7tYm2NM"
title = "A Quick Announcement and Some Thank Yous!"

[[input.files]]
path = "1nsU5-aXmfp_heVcOFZ0CodbaGwB14FaMAHyaH6gIGkA.txt"
url = "1nsU5-aXmfp_heVcOFZ0CodbaGwB14FaMAHyaH6gIGkA"
title = "COUNTER/Weight 44: Live Post-Mortem"

