[input]
base_directory = "transcripts/extras"
url_prefix = "https://docs.google.com/document/d/"
stemming = "None"
[[input.files]]
path = "1CmJK8xDiMuo0U1myXgs6rRCsCDMWy2EXwdKgHOPUCqM.txt"
url = "1CmJK8xDiMuo0U1myXgs6rRCsCDMWy2EXwdKgHOPUCqM"
title = "Live at the Table - Fall of Magic Pt 1"

[[input.files]]
path = "13mdjYiz5SSjQqP0VLiTaIY1H2MUEd7_5ICItJZRChRc.txt"
url = "13mdjYiz5SSjQqP0VLiTaIY1H2MUEd7_5ICItJZRChRc"
title = "Live at the Table - Fall of Magic Pt 2"

[[input.files]]
path = "1cBVYzcjasZqXBPfoy08zzvzcz1YJEcHhliQF0ykx5vY.txt"
url = "1cBVYzcjasZqXBPfoy08zzvzcz1YJEcHhliQF0ykx5vY"
title = "Live at the Table - Fall of Magic Pt 3"

[[input.files]]
path = "1IFgIgQ5gLCZ3JcO4Bg9aH--GTXi0l4Ih_y-9hro4wkU.txt"
url = "1IFgIgQ5gLCZ3JcO4Bg9aH--GTXi0l4Ih_y-9hro4wkU"
title = "Bluff City Teaser"

[[input.files]]
path = "1hkYy98MAG7OOb3qao7plqwTGH2hlJLBbe9_6k7VRFwc.txt"
url = "1hkYy98MAG7OOb3qao7plqwTGH2hlJLBbe9_6k7VRFwc"
title = "Bluff City 01: A Bowling Alley, A Boxer, and A Bird Pt. 1"

