[input]
base_directory = "transcripts/marielda"
url_prefix = "https://docs.google.com/document/d/"
stemming = "None"
[[input.files]]
path = "1YNrFWHqMYMbpoPgXNusPhCQ7pw4q7-K6jDjGE4wt0Qo.txt"
url = "1YNrFWHqMYMbpoPgXNusPhCQ7pw4q7-K6jDjGE4wt0Qo"
title = "Marielda 01: The City of Light Pt. 1"

[[input.files]]
path = "1b_Wwzcd7orjAa_KkCgtHcdVJYEieQtsX6n1kq-TgW4g.txt"
url = "1b_Wwzcd7orjAa_KkCgtHcdVJYEieQtsX6n1kq-TgW4g"
title = "Marielda 02: The City of Light Pt. 2"

[[input.files]]
path = "1_QJyConmw9eMg3ZmRe5MexHev_vIIB7K4hqTaIv_FYQ.txt"
url = "1_QJyConmw9eMg3ZmRe5MexHev_vIIB7K4hqTaIv_FYQ"
title = "Marielda 03: The Crosstown Job Pt. 1"

[[input.files]]
path = "1-0h-w9oQkZZWXiAtC5TYD-9grZsXyI4rv6VFKqUKgzY.txt"
url = "1-0h-w9oQkZZWXiAtC5TYD-9grZsXyI4rv6VFKqUKgzY"
title = "Marielda 04: The Crosstown Job Pt. 2"

[[input.files]]
path = "1PUocibul92TqMnoFeia5n1gVF9YNyN6QDPVsICskTho.txt"
url = "1PUocibul92TqMnoFeia5n1gVF9YNyN6QDPVsICskTho"
title = "Marielda 05: War and Azaleas"

[[input.files]]
path = "1UFSICn5iLXzO9EEfyWXptpsiYpPM2BYsOs8So-CbLlo.txt"
url = "1UFSICn5iLXzO9EEfyWXptpsiYpPM2BYsOs8So-CbLlo"
title = "Marielda 06: The Valentine Affair Pt. 1"

[[input.files]]
path = "1eMyiu3G9MCwJRfvRSIsV1KrZEfsMS6Cc53kUzr4pDmw.txt"
url = "1eMyiu3G9MCwJRfvRSIsV1KrZEfsMS6Cc53kUzr4pDmw"
title = "Marielda 07: The Valentine Affair Pt. 2"

[[input.files]]
path = "1rytp_f9d6JWy0z5W-HRFy1IijVWALrt6c7h4czCpZLw.txt"
url = "1rytp_f9d6JWy0z5W-HRFy1IijVWALrt6c7h4czCpZLw"
title = "Marielda 08: The Valentine Affair Pt. 3"

[[input.files]]
path = "1Pt-wDU0wuksgrvTgQLMXOlI11KidU11ebi5oAZ0CF08.txt"
url = "1Pt-wDU0wuksgrvTgQLMXOlI11KidU11ebi5oAZ0CF08"
title = "Marielda 09: The Valentine Affair Pt. 4"

[[input.files]]
path = "1FZbTPPG_vD6f7eUTAC2jH-IoLBdbB8nneyUuzv_AZzs.txt"
url = "1FZbTPPG_vD6f7eUTAC2jH-IoLBdbB8nneyUuzv_AZzs"
title = "Marielda 10: Four Conversations"

[[input.files]]
path = "1kwOiYc1-bFyOXQHgHFzyJnF4mTOcZfUnMVeADTCW_8Q.txt"
url = "1kwOiYc1-bFyOXQHgHFzyJnF4mTOcZfUnMVeADTCW_8Q"
title = "Marielda 11: The Killing of the King-God Samothes By The Traitor Prince Maelgwyn Pt. 1"

[[input.files]]
path = "1TzLo8-waXbBWK4okB1KaIV5XqgrCejN95gcaZf16nnA.txt"
url = "1TzLo8-waXbBWK4okB1KaIV5XqgrCejN95gcaZf16nnA"
title = "Marielda 12: The Killing of the King-God Samothes By The Traitor Prince Maelgwyn Pt. 2"

[[input.files]]
path = "1Q-rOAsZutI01ERj5TfWUG56XNP_V8rPkuokkdgr8vrY.txt"
url = "1Q-rOAsZutI01ERj5TfWUG56XNP_V8rPkuokkdgr8vrY"
title = "Marielda 13: The Killing of the King-God Samothes By The Traitor Prince Maelgwyn Pt. 3"

[[input.files]]
path = "1vzWYoApFwjl4Kqahgo5uTpEdNanF23vX5Gf31uCneVo.txt"
url = "1vzWYoApFwjl4Kqahgo5uTpEdNanF23vX5Gf31uCneVo"
title = "Marielda 14: The Killing of the King-God Samothes By The Traitor Prince Maelgwyn Pt. 4"

[[input.files]]
path = "1JopXR_a4qCx_g029o5Rvxmie3c1hcuq0U7eBHHTQrM4.txt"
url = "1JopXR_a4qCx_g029o5Rvxmie3c1hcuq0U7eBHHTQrM4"
title = "A Message From Austin"

[[input.files]]
path = "1YBxr-6x381QQwcjOR5Oq-57fkjJuTKgVVDPvXpVfjho.txt"
url = "1YBxr-6x381QQwcjOR5Oq-57fkjJuTKgVVDPvXpVfjho"
title = "A Message From Ali"

