[input]
base_directory = "transcripts/sangfielle"
url_prefix = "https://docs.google.com/document/d/"
stemming = "None"
[[input.files]]
path = "1TJpUD-ezhHZDmt6YPkqJ2GcA__TZf8UfJFVdQsSqOQc.txt"
url = "1TJpUD-ezhHZDmt6YPkqJ2GcA__TZf8UfJFVdQsSqOQc"
title = "Season 7 Trailer & Announcement"

[[input.files]]
path = "162v2Do07dxo9TxfI-bFzmN-XwBqvoYKTW11j7gzuWqU.txt"
url = "162v2Do07dxo9TxfI-bFzmN-XwBqvoYKTW11j7gzuWqU"
title = "Sangfielle 01: The Curse of Eastern Folly Pt. 1"

[[input.files]]
path = "11BY5ajVD2DkR0nKkbCiYPPb_boaPWC_7urW0vIerQI4.txt"
url = "11BY5ajVD2DkR0nKkbCiYPPb_boaPWC_7urW0vIerQI4"
title = "Sangfielle 02: The Curse of Eastern Folly Pt. 2"

[[input.files]]
path = "1zczvM89ydLIZxwTbihU9O041TBcaHWX-qsTnRF2CvcI.txt"
url = "1zczvM89ydLIZxwTbihU9O041TBcaHWX-qsTnRF2CvcI"
title = "Sangfielle 03: The Curse of Eastern Folly Pt. 3"

[[input.files]]
path = "1AUXhp-q9f1s1xG0JDC-qhWQkFokFZjHTk81hKs41xnM.txt"
url = "1AUXhp-q9f1s1xG0JDC-qhWQkFokFZjHTk81hKs41xnM"
title = "Sangfielle 04: The Blackwick Group"

[[input.files]]
path = "1wShi5uvYHOEpNIZgF0JuNXLFEQmK6FGnG_kMFhVsZRA.txt"
url = "1wShi5uvYHOEpNIZgF0JuNXLFEQmK6FGnG_kMFhVsZRA"
title = "Sangfielle 06: The Hymn of the Mother-Beast Pt. 2"

[[input.files]]
path = "1Hy68u6GQNEMfAhPqATFcF4Dv5Jqk1Jd01b_XNO3SvDk.txt"
url = "1Hy68u6GQNEMfAhPqATFcF4Dv5Jqk1Jd01b_XNO3SvDk"
title = "Sangfielle 07: The Hymn of the Mother-Beast Pt. 3"

[[input.files]]
path = "1U-4KpK9j_7I4i0iPoEvTobASAxCTJKOlyv6cf86E9ZM.txt"
url = "1U-4KpK9j_7I4i0iPoEvTobASAxCTJKOlyv6cf86E9ZM"
title = "Sangfielle 08: The Hymn of the Mother-Beast Pt. 4"

[[input.files]]
path = "1FwP8KkRHaH-0WOK-eKMNyNSZQsEc86MqZaVelbazS-c.txt"
url = "1FwP8KkRHaH-0WOK-eKMNyNSZQsEc86MqZaVelbazS-c"
title = "Sangfielle 10: The Secret Ledger of Roseroot Hall Pt. 2"

[[input.files]]
path = "1O7-ytnphNdpn5D1zLJXgviWrDUTYxs9PJoQd3xhPzCg.txt"
url = "1O7-ytnphNdpn5D1zLJXgviWrDUTYxs9PJoQd3xhPzCg"
title = "Sangfielle 11: The Secret Ledger of Roseroot Hall Pt. 3"

[[input.files]]
path = "1G3OUBiskuTTkJYudxbCjuIFtyE5FOnngzi37vbizkFQ.txt"
url = "1G3OUBiskuTTkJYudxbCjuIFtyE5FOnngzi37vbizkFQ"
title = "Sangfielle 12: The Secret Ledger of Roseroot Hall Pt. 4"

[[input.files]]
path = "1yoCrscfk-5k8IaM_6T0RXuXDBgyAJeBTcgY0ToeKE0w.txt"
url = "1yoCrscfk-5k8IaM_6T0RXuXDBgyAJeBTcgY0ToeKE0w"
title = "Sangfielle 13: Market Day in Blackwick"

[[input.files]]
path = "1H2HNCdwZw05GlvkgL9WVY7TkX4GplgACFTqSZyGF7-A.txt"
url = "1H2HNCdwZw05GlvkgL9WVY7TkX4GplgACFTqSZyGF7-A"
title = "Sangfielle 14: The Candle Factory Pt. 1"

[[input.files]]
path = "16p8PRryW2y1NuAFO4c_i86C_pmJgT6h7PM0z2oyctjc.txt"
url = "16p8PRryW2y1NuAFO4c_i86C_pmJgT6h7PM0z2oyctjc"
title = "Sangfielle 15: The Candle Factory Pt. 2"

[[input.files]]
path = "1mYD3ArDEElAOm05NEU4FefmC7L7zCW1-vk64iK11Xf0.txt"
url = "1mYD3ArDEElAOm05NEU4FefmC7L7zCW1-vk64iK11Xf0"
title = "Sangfielle 16: The Candle Factory Pt. 3"

[[input.files]]
path = "1YMfPjKnmsCyYjqXFJzw_ENyrLKTJkiKLiW89-4qA2UQ.txt"
url = "1YMfPjKnmsCyYjqXFJzw_ENyrLKTJkiKLiW89-4qA2UQ"
title = "Sangfielle 17: What Happened at Bell Metal Station Pt. 1"

[[input.files]]
path = "1aXI7ibRIZaI_eWsoxVxqUx1f3YjoGyVH2dcl2noAyv4.txt"
url = "1aXI7ibRIZaI_eWsoxVxqUx1f3YjoGyVH2dcl2noAyv4"
title = "Sangfielle 18: What Happened at Bell Metal Station Pt. 2"

[[input.files]]
path = "11neQMzcBxYBoQVA8X83QXVfdUfJBZEd6y9pOSPJUm4U.txt"
url = "11neQMzcBxYBoQVA8X83QXVfdUfJBZEd6y9pOSPJUm4U"
title = "Sangfielle 19: What Happened at Bell Metal Station Pt. 3"

[[input.files]]
path = "1x-UJLsUgkoyvvRXrjsY-qux6qiM4ld6jiOltrXuggWU.txt"
url = "1x-UJLsUgkoyvvRXrjsY-qux6qiM4ld6jiOltrXuggWU"
title = "Sangfielle 20: What Happened at Bell Metal Station Pt. 4"

[[input.files]]
path = "199e9j4q2nNn8TQVy-28-hKREFCIYWPWaf56UQorcsLY.txt"
url = "199e9j4q2nNn8TQVy-28-hKREFCIYWPWaf56UQorcsLY"
title = "Sangfielle 21: At the Gates of Sapodilla"

[[input.files]]
path = "1eGea-QPKYJdr7OEvJg5AjtNiq3twEBHE6Lq3nEB5yrI.txt"
url = "1eGea-QPKYJdr7OEvJg5AjtNiq3twEBHE6Lq3nEB5yrI"
title = "Sangfielle 22: Whispers in the City by the Sea"

[[input.files]]
path = "1kJGTDu2kpmutiQEGhguBSwfsRJKv3ZWu2p_sAI7pBbM.txt"
url = "1kJGTDu2kpmutiQEGhguBSwfsRJKv3ZWu2p_sAI7pBbM"
title = "Sangfielle 23: The Perpetual Oratorio of Davia Pledge Pt. 1"

[[input.files]]
path = "1eqERmTIy7toxiYA3PjHEmSi2A7tsrODoEqjMPS2srJk.txt"
url = "1eqERmTIy7toxiYA3PjHEmSi2A7tsrODoEqjMPS2srJk"
title = "Sangfielle 24: The Perpetual Oratorio of Davia Pledge Pt. 2"

[[input.files]]
path = "1wFTZhZmiho7H7EbgsgWCzdrV2cYvOhMB4ZnpqPq9-Ro.txt"
url = "1wFTZhZmiho7H7EbgsgWCzdrV2cYvOhMB4ZnpqPq9-Ro"
title = "Sangfielle 25: The Perpetual Oratorio of Davia Pledge Pt. 3"

[[input.files]]
path = "1WHGvq92T9PD4K2aB_69yqyXaJr98w85Hdy9x1a4BoI8.txt"
url = "1WHGvq92T9PD4K2aB_69yqyXaJr98w85Hdy9x1a4BoI8"
title = "Sangfielle 26: The Perpetual Oratorio of Davia Pledge Pt. 4"

[[input.files]]
path = "140fGYZguKzdHZLlXPlMwVUgoJXHU2AC3dK4Y-l_4ReQ.txt"
url = "140fGYZguKzdHZLlXPlMwVUgoJXHU2AC3dK4Y-l_4ReQ"
title = "Sangfielle 27: The Perpetual Oratorio of Davia Pledge Pt. 5"

[[input.files]]
path = "1_UpVBpmftWycCH4jbkJ3f4KMH8m8IrCxyfBA_XntQ0M.txt"
url = "1_UpVBpmftWycCH4jbkJ3f4KMH8m8IrCxyfBA_XntQ0M"
title = "Sangfielle 28: Hark! The Citadel Beneath Pt. 1"

[[input.files]]
path = "1PbZjJFhbvHT_k6vAz9XBNIdAXzPNJjh0a1HayZHLM_4.txt"
url = "1PbZjJFhbvHT_k6vAz9XBNIdAXzPNJjh0a1HayZHLM_4"
title = "Sangfielle 29: Hark! The Citadel Beneath Pt. 2"

[[input.files]]
path = "1DfipGvp0YvA98cGtFjOMJLXqFF7U7Pi2NBFDn92kHoc.txt"
url = "1DfipGvp0YvA98cGtFjOMJLXqFF7U7Pi2NBFDn92kHoc"
title = "Sangfielle 30: Hark! The Citadel Beneath Pt. 3"

[[input.files]]
path = "1GC3bLozCOeDoVDNP2Y7BRER6ctW1iTqvKssCvdfk43U.txt"
url = "1GC3bLozCOeDoVDNP2Y7BRER6ctW1iTqvKssCvdfk43U"
title = "Sangfielle 31: Hark! The Citadel Beneath Pt. 4"

[[input.files]]
path = "1iXIxDJVR--ai2BCiRHGfH0qNrz_d3DmgmT-u-HnuPdM.txt"
url = "1iXIxDJVR--ai2BCiRHGfH0qNrz_d3DmgmT-u-HnuPdM"
title = "Sangfielle 32: Passage on the Jade Moon Pt. 1"

[[input.files]]
path = "1dDob_JO5ZidSwgSZUGGeJRQ4q5Wcy4IgaUpGk5I47OA.txt"
url = "1dDob_JO5ZidSwgSZUGGeJRQ4q5Wcy4IgaUpGk5I47OA"
title = "Sangfielle 33: Passage on the Jade Moon Pt. 2"

[[input.files]]
path = "1cYQN6rZ9oZABA0V0mNoBDsPcDpapA7YeO_Hk4UAQPc8.txt"
url = "1cYQN6rZ9oZABA0V0mNoBDsPcDpapA7YeO_Hk4UAQPc8"
title = "Sangfielle 34: Passage on the Jade Moon Pt. 3"

[[input.files]]
path = "1BQb6V7KYXHyV7TvGXyp7Ati-7zR6xbSIbjHR0twFhUw.txt"
url = "1BQb6V7KYXHyV7TvGXyp7Ati-7zR6xbSIbjHR0twFhUw"
title = "Sangfielle 35: Marrow in the Field"

[[input.files]]
path = "1Ge0s12mhTnxDssOLkq06PRd8lQ9AIzrU5KW-RYXYs6w.txt"
url = "1Ge0s12mhTnxDssOLkq06PRd8lQ9AIzrU5KW-RYXYs6w"
title = "Sangfielle 36: Marrow in the Bone"

[[input.files]]
path = "1emRC8y91Ti6O9Hwp-LHD2WOje2ALgAhnp_MOU3uFCd4.txt"
url = "1emRC8y91Ti6O9Hwp-LHD2WOje2ALgAhnp_MOU3uFCd4"
title = "Sangfielle 37: Just Returns Pt. 1"

[[input.files]]
path = "1ANpgmlX8EhfiPNXt3QIqqSZ7-YCakf_fb3Gnx0eGOUg.txt"
url = "1ANpgmlX8EhfiPNXt3QIqqSZ7-YCakf_fb3Gnx0eGOUg"
title = "Sangfielle 38: Just Returns Pt. 2"

[[input.files]]
path = "1TBvdm_rM8oxjpUXuqKsHeRQ3EWvRGpHJY8V-lWnaOG4.txt"
url = "1TBvdm_rM8oxjpUXuqKsHeRQ3EWvRGpHJY8V-lWnaOG4"
title = "Sangfielle 39: Just Returns Pt. 3"

[[input.files]]
path = "11w25DsBG3Z6MAVi898Xw4MlCOZpTT4yBtaBnxvHtkzQ.txt"
url = "11w25DsBG3Z6MAVi898Xw4MlCOZpTT4yBtaBnxvHtkzQ"
title = "Sangfielle 40: Just Returns Pt. 4"

[[input.files]]
path = "1iqdP9nvw9zX7Vehvh1fCmTQD2NoYkSfs9iYqWGd567g.txt"
url = "1iqdP9nvw9zX7Vehvh1fCmTQD2NoYkSfs9iYqWGd567g"
title = "Sangfielle 41: Just Returns Pt. 5"

[[input.files]]
path = "1LNn1r6GxqvSS2A4kllxhTvkn4yeuuoQbw_PoI5KrCEQ.txt"
url = "1LNn1r6GxqvSS2A4kllxhTvkn4yeuuoQbw_PoI5KrCEQ"
title = "Sangfielle 42: Two Kinds of Quarry Pt. 1"

[[input.files]]
path = "1gZhQJV0AgJzRa1B-4n7i9t-rwtj0q4F9ccCZCW4yLbA.txt"
url = "1gZhQJV0AgJzRa1B-4n7i9t-rwtj0q4F9ccCZCW4yLbA"
title = "Sangfielle 43: Two Kinds of Quarry Pt. 2"

