[input]
base_directory = "transcripts/twilight-mirage"
url_prefix = "https://docs.google.com/document/d/"
stemming = "None"
[[input.files]]
path = "1sUis9SBhgH6ALDkruEFx_jNg5RvZ4Sk3fMSpBaf6DMw.txt"
url = "1sUis9SBhgH6ALDkruEFx_jNg5RvZ4Sk3fMSpBaf6DMw"
title = "Twilight Mirage 00: The Final Eight Divines"

[[input.files]]
path = "1wMbqJgBTkq1iCJsojt4mhi53vgnkd-h8utfz42F9RDE.txt"
url = "1wMbqJgBTkq1iCJsojt4mhi53vgnkd-h8utfz42F9RDE"
title = "Twilight Mirage 01: The Beloved Dust"

[[input.files]]
path = "1xheU5Dfpx0Jep_E98yRN2AE3W2cT9Nb1Gcc3CmnA-IE.txt"
url = "1xheU5Dfpx0Jep_E98yRN2AE3W2cT9Nb1Gcc3CmnA-IE"
title = "Twilight Mirage 02: The Last Divine"

[[input.files]]
path = "18p9IoShDykNOabu7mEV_g86d0BvRJkxsTXZg7hq2H_Y.txt"
url = "18p9IoShDykNOabu7mEV_g86d0BvRJkxsTXZg7hq2H_Y"
title = "Twilight Mirage 03: The Planet of Quire"

[[input.files]]
path = "1QgUDzt2DEnQ7RknfbZasjdtMFucFNLJc9LvD6NO7b_k.txt"
url = "1QgUDzt2DEnQ7RknfbZasjdtMFucFNLJc9LvD6NO7b_k"
title = "Twilight Mirage 04: Birds of Prey"

[[input.files]]
path = "1ZXY8ppz03W0zlo6sAZP7za-yO8Hys6UJ-cGm8TNUuGo.txt"
url = "1ZXY8ppz03W0zlo6sAZP7za-yO8Hys6UJ-cGm8TNUuGo"
title = "Twilight Mirage 05: The Sunlight of Knowing"

[[input.files]]
path = "1Ec9DpAOXCbfNM6pxCbYV-RxUH7e8RjxIJ--J0WJZ9hs.txt"
url = "1Ec9DpAOXCbfNM6pxCbYV-RxUH7e8RjxIJ--J0WJZ9hs"
title = "Twilight Mirage 06: We Want You To Come Home"

[[input.files]]
path = "1QeA5wmSE1ADw_kGPwWDe9c8_9mOmShymCpSqO4xoFkc.txt"
url = "1QeA5wmSE1ADw_kGPwWDe9c8_9mOmShymCpSqO4xoFkc"
title = "Twilight Mirage 07: Second Street Drifting"

[[input.files]]
path = "1HzWQB1vZuXpEv87mXUeFLCScqs2uU330P8C1wqNM3hw.txt"
url = "1HzWQB1vZuXpEv87mXUeFLCScqs2uU330P8C1wqNM3hw"
title = "Twilight Mirage 08: We are the River, And it is the Sea"

[[input.files]]
path = "1XWBJHqCYqnCZAak7_O5qPWKP_BxaVdjvs-SH1B8FVt0.txt"
url = "1XWBJHqCYqnCZAak7_O5qPWKP_BxaVdjvs-SH1B8FVt0"
title = "Twilight Mirage 09: The Sound of Strings"

[[input.files]]
path = "1vW25xDUrFWBVWw1_Mt2aX8Kdm0MbYf3ezcVTC80EeE4.txt"
url = "1vW25xDUrFWBVWw1_Mt2aX8Kdm0MbYf3ezcVTC80EeE4"
title = "Twilight Mirage 10: Looking To Land"

[[input.files]]
path = "1xkQHDb8Dfaafr9rpmjA7aiiNTKDbaxrPgQOUhzROmGM.txt"
url = "1xkQHDb8Dfaafr9rpmjA7aiiNTKDbaxrPgQOUhzROmGM"
title = "Twilight Mirage 11: What We're Capable Of"

[[input.files]]
path = "1FjBp_WmFXLHLKdiiKcJ01U1ZASbxtTGhQdO6la-A7ME.txt"
url = "1FjBp_WmFXLHLKdiiKcJ01U1ZASbxtTGhQdO6la-A7ME"
title = "Twilight Mirage 12: The Promise of Presence"

[[input.files]]
path = "1r26GNDkvZOqO8-O4lFcX1WV3WPAG-c7Gij-y4p_fDgY.txt"
url = "1r26GNDkvZOqO8-O4lFcX1WV3WPAG-c7Gij-y4p_fDgY"
title = "Twilight Mirage 13: An Instinct Without A Word"

[[input.files]]
path = "1dWYhP7maRexQDS8kcA_JbFzMy-E6oRXGawiCwh4M63U.txt"
url = "1dWYhP7maRexQDS8kcA_JbFzMy-E6oRXGawiCwh4M63U"
title = "Twilight Mirage 14: The Value of Distance"

[[input.files]]
path = "1C6LJmoKS5FroMy2C9u7WTU6NpxTnJ-dKpmT1QrVLTLE.txt"
url = "1C6LJmoKS5FroMy2C9u7WTU6NpxTnJ-dKpmT1QrVLTLE"
title = "Twilight Mirage 15: A Life and A History"

[[input.files]]
path = "1_uK0HyqKx0rQJsRoDtWOKm6favwdg9h8fn9-qRATZlw.txt"
url = "1_uK0HyqKx0rQJsRoDtWOKm6favwdg9h8fn9-qRATZlw"
title = "Twilight Mirage 16: An Approximation of a Connection"

[[input.files]]
path = "1pc2QQX6QUep70rhsuNg45n_-xOfLCr-QYjutpocZ6n8.txt"
url = "1pc2QQX6QUep70rhsuNg45n_-xOfLCr-QYjutpocZ6n8"
title = "Twilight Mirage 17: Like Falling Leaves"

[[input.files]]
path = "11K_pirBG5hxnlegizPSq9Sj-PkarfVMATe5FLoqLc1A.txt"
url = "11K_pirBG5hxnlegizPSq9Sj-PkarfVMATe5FLoqLc1A"
title = "Twilight Mirage 18: The Sun Pales to Its Brightness"

[[input.files]]
path = "1fjdzcgOoyZ0WrvjThJ_KPnXrXZ5Fp4-U1xbVLFZQWh8.txt"
url = "1fjdzcgOoyZ0WrvjThJ_KPnXrXZ5Fp4-U1xbVLFZQWh8"
title = "Twilight Mirage 19: A Single Moment, Caught"

[[input.files]]
path = "1-xgJnGuw0mTozrIJDUkIoxP0Jpg1uyvJQIjnAc2DdMY.txt"
url = "1-xgJnGuw0mTozrIJDUkIoxP0Jpg1uyvJQIjnAc2DdMY"
title = "Twilight Mirage 20: Bits Left Behind"

[[input.files]]
path = "11rMeHwvC6YTzKNjvcFCl6pBICt4G9EI9c3bdmOxPbTc.txt"
url = "11rMeHwvC6YTzKNjvcFCl6pBICt4G9EI9c3bdmOxPbTc"
title = "Twilight Mirage 21: One's Own Right"

[[input.files]]
path = "1muwtbtGzAsGTlMWcnGJeUB9ucaPRYjjmByJ4vwmJ9oQ.txt"
url = "1muwtbtGzAsGTlMWcnGJeUB9ucaPRYjjmByJ4vwmJ9oQ"
title = "Twilight Mirage 22: godspeed, glory Pt. 1"

[[input.files]]
path = "1wU_sQ0DY8StcyGJykN9LsJ0pAcfeHIx_1c8c6r5vGp8.txt"
url = "1wU_sQ0DY8StcyGJykN9LsJ0pAcfeHIx_1c8c6r5vGp8"
title = "Twilight Mirage 23: godspeed, glory Pt. 2"

[[input.files]]
path = "1dTZNobzzspfajnJV32P00wcwtMjDiYl83x5l9t71x9Q.txt"
url = "1dTZNobzzspfajnJV32P00wcwtMjDiYl83x5l9t71x9Q"
title = "Twilight Mirage 24: godspeed, glory Pt. 3"

[[input.files]]
path = "1NUdc9oHDttp8XNIGvGUdWDk8kHPzfMDYBqWjnQdT-bE.txt"
url = "1NUdc9oHDttp8XNIGvGUdWDk8kHPzfMDYBqWjnQdT-bE"
title = "Twilight Mirage 25: The Miracle of the Mirage: The Dragon"

[[input.files]]
path = "19VwaLwuiWD90Y6KGVjJ1Z914APgpeGKI-eyhoXH9Vkc.txt"
url = "19VwaLwuiWD90Y6KGVjJ1Z914APgpeGKI-eyhoXH9Vkc"
title = "Twilight Mirage 26: The Miracle of the Mirage: The Heist"

[[input.files]]
path = "1EBnNWYGS0mBluIvhTguvxjGk8DIgp-9FxMIme1YRgV4.txt"
url = "1EBnNWYGS0mBluIvhTguvxjGk8DIgp-9FxMIme1YRgV4"
title = "Twilight Mirage 27: The Miracle of the Mirage: The Siege"

[[input.files]]
path = "1lTmS4TdtfEeoN1wPlDmz9JfnAXz9E6J6_Qp3L-VdQxk.txt"
url = "1lTmS4TdtfEeoN1wPlDmz9JfnAXz9E6J6_Qp3L-VdQxk"
title = "Twilight Mirage 28: This Year of Ours: The Scoundrel"

[[input.files]]
path = "1rmrBcI70ZO0yuLi_6Rf5-eph8eEa2iICxcl4G85NrAA.txt"
url = "1rmrBcI70ZO0yuLi_6Rf5-eph8eEa2iICxcl4G85NrAA"
title = "Twilight Mirage 29: This Year of Ours: The Pilot"

[[input.files]]
path = "1x6RuF1UG5l3wPs2lQDTIXs30ysIE7w2G2q0pviVlqII.txt"
url = "1x6RuF1UG5l3wPs2lQDTIXs30ysIE7w2G2q0pviVlqII"
title = "Twilight Mirage 30: This Year of Ours: The Muscle"

[[input.files]]
path = "1Ruii5niyvSzlkWqvMLYPFp3_SKDnDuAiSEG2dG8H8GY.txt"
url = "1Ruii5niyvSzlkWqvMLYPFp3_SKDnDuAiSEG2dG8H8GY"
title = "Twilight Mirage 31: This Year of Ours: The Mechanic"

[[input.files]]
path = "1WVpr7fNLhJeAhvrpbTwMAkyUQMFSBO5EjxnSrbC2EfY.txt"
url = "1WVpr7fNLhJeAhvrpbTwMAkyUQMFSBO5EjxnSrbC2EfY"
title = "Twilight Mirage 32: This Year of Ours: The Stitch"

[[input.files]]
path = "11qZTwYvzPOwspWHutp4JUFMfzUjeCqKMHilwTrUd5ig.txt"
url = "11qZTwYvzPOwspWHutp4JUFMfzUjeCqKMHilwTrUd5ig"
title = "Twilight Mirage 33: This Year of Ours: The Speaker"

[[input.files]]
path = "1DievgnHN1OujJN97CcmuyG0Vm45sMDF9yum2C1nWKg8.txt"
url = "1DievgnHN1OujJN97CcmuyG0Vm45sMDF9yum2C1nWKg8"
title = "Twilight Mirage 34: This Year of Ours: The Mystic"

[[input.files]]
path = "102V1dLuBS5xToyRnZNeMpU7j7Eth4PFYV-8a7iRP5ec.txt"
url = "102V1dLuBS5xToyRnZNeMpU7j7Eth4PFYV-8a7iRP5ec"
title = "Twilight Mirage 35: This Year of Ours: The Notion"

[[input.files]]
path = "1V3hm5PNQ7fMfx97jKdknmcA43clTRn0vi5fgGIJ4yVg.txt"
url = "1V3hm5PNQ7fMfx97jKdknmcA43clTRn0vi5fgGIJ4yVg"
title = "Twilight Mirage 36: Every Bad Idea"

[[input.files]]
path = "1Ypfpyjn_q4SvgmDslE0qDgKqWxKccYtZ0Gn3ArS3ZmE.txt"
url = "1Ypfpyjn_q4SvgmDslE0qDgKqWxKccYtZ0Gn3ArS3ZmE"
title = "Twilight Mirage 37: Along A Route"

[[input.files]]
path = "15AR_aE5HvnQg7GOcyCnpc74lg_Qe_2eXvCINtRLlisQ.txt"
url = "15AR_aE5HvnQg7GOcyCnpc74lg_Qe_2eXvCINtRLlisQ"
title = "Twilight Mirage 38: The Good Decision"

[[input.files]]
path = "126-HIvguGKXAAe-4xjcMYhtXMSNXRQ9-oE3fx2valvM.txt"
url = "126-HIvguGKXAAe-4xjcMYhtXMSNXRQ9-oE3fx2valvM"
title = "Twilight Mirage 39: Staying Neutral"

[[input.files]]
path = "1EMXqJ9OjF4PnpVdpdJFG4HL-fE1q0GAA8qfa3Xf6pwA.txt"
url = "1EMXqJ9OjF4PnpVdpdJFG4HL-fE1q0GAA8qfa3Xf6pwA"
title = "Twilight Mirage 40: Like What We Used To Do"

[[input.files]]
path = "1u2yE26gTUTfOSe5z3__ixaKZVaoWNay2vShPsm-Pma8.txt"
url = "1u2yE26gTUTfOSe5z3__ixaKZVaoWNay2vShPsm-Pma8"
title = "Twilight Mirage 41: No Value in a Closed Door"

[[input.files]]
path = "1ojeWmu2G4vcosYt6ogMc37L4FD4lJWmV9HVkVF_HPss.txt"
url = "1ojeWmu2G4vcosYt6ogMc37L4FD4lJWmV9HVkVF_HPss"
title = "Twilight Mirage 42: Look the Other Way"

[[input.files]]
path = "15XJs4CnwDeYeA81DQhREkHIbESomTD78K7lg2JHbz00.txt"
url = "15XJs4CnwDeYeA81DQhREkHIbESomTD78K7lg2JHbz00"
title = "Twilight Mirage 43: The Center of the Storm"

[[input.files]]
path = "14FJSegQmxxJwk-IsaWtmftqSLVRoyNTCN5cFe7m31VI.txt"
url = "14FJSegQmxxJwk-IsaWtmftqSLVRoyNTCN5cFe7m31VI"
title = "Twilight Mirage 44: The Pathways in the Woods"

[[input.files]]
path = "13eAcu_jCDdzBbOHigCg_zpnwmjSDJqlL5l3ePSQeSVs.txt"
url = "13eAcu_jCDdzBbOHigCg_zpnwmjSDJqlL5l3ePSQeSVs"
title = "Twilight Mirage 45: Downtime on Gift-3"

[[input.files]]
path = "1ehRz-hnFXLKhzHkoQjDjenDR-8q_W9imcXHeXpg93e4.txt"
url = "1ehRz-hnFXLKhzHkoQjDjenDR-8q_W9imcXHeXpg93e4"
title = "Twilight Mirage 46: Every Time We Leave, It Changes"

[[input.files]]
path = "1o1f5M75c47NCZEdVxUSvNGtCX3HHBJiuvjfYPgVJm14.txt"
url = "1o1f5M75c47NCZEdVxUSvNGtCX3HHBJiuvjfYPgVJm14"
title = "Twilight Mirage 47: Uncontrolled Fires"

[[input.files]]
path = "1bKXr1xq0v0lqhDpZrcDC3HMkkeMYB7ld_ZENMfjZJDQ.txt"
url = "1bKXr1xq0v0lqhDpZrcDC3HMkkeMYB7ld_ZENMfjZJDQ"
title = "Twilight Mirage 48: This Place Pushes Back"

[[input.files]]
path = "13pJjzr4N-lEEF4MMU3tptv2ptIOeZUqTKzZ5SSyYtA4.txt"
url = "13pJjzr4N-lEEF4MMU3tptv2ptIOeZUqTKzZ5SSyYtA4"
title = "Twilight Mirage 49: Bona Fide, Good Faith"

[[input.files]]
path = "1c-74rr13dxi0NkwSakhgcVwkqx90Jk5Yn7LWbyOtp0g.txt"
url = "1c-74rr13dxi0NkwSakhgcVwkqx90Jk5Yn7LWbyOtp0g"
title = "Twilight Mirage 50: A Very Old Mistake"

[[input.files]]
path = "14LkFDs1O4qC7W_isx9TRSOA9LZVBtnsUg3LpHoc6pak.txt"
url = "14LkFDs1O4qC7W_isx9TRSOA9LZVBtnsUg3LpHoc6pak"
title = "Twilight Mirage 51: Open As Possible"

[[input.files]]
path = "1V2VwYw9np5bfYjHCoLMi2kj3-f4-Ds6h15-ZEDdt6gE.txt"
url = "1V2VwYw9np5bfYjHCoLMi2kj3-f4-Ds6h15-ZEDdt6gE"
title = "Twilight Mirage 52: The Second Miracle"

[[input.files]]
path = "130xmSpDZGZWaA3PADhs6Y9tZjrDlQHfx9uLgavw2-1o.txt"
url = "130xmSpDZGZWaA3PADhs6Y9tZjrDlQHfx9uLgavw2-1o"
title = "Twilight Mirage 53: Our Flaws in a Vacuum, or the Promise We Made To Each Other"

[[input.files]]
path = "1vwkjib7IghpPvQiLt-SHsatZwKX_Owptwje5PLNZ7hA.txt"
url = "1vwkjib7IghpPvQiLt-SHsatZwKX_Owptwje5PLNZ7hA"
title = "Twilight Mirage 54: Downtime on Skein"

[[input.files]]
path = "1jomv54LIQ2D75D-R7cseONE8NR8ShZp1BQhCRL5OTEE.txt"
url = "1jomv54LIQ2D75D-R7cseONE8NR8ShZp1BQhCRL5OTEE"
title = "Twilight Mirage 55: The Vault of Anticipation Pt. 1"

[[input.files]]
path = "1K4LAEvIoTeiwvs8XyAKazbAOqa341kNsmu34tcUT4tc.txt"
url = "1K4LAEvIoTeiwvs8XyAKazbAOqa341kNsmu34tcUT4tc"
title = "Twilight Mirage 56: The Vault of Anticipation Pt. 2"

[[input.files]]
path = "1M22mtskeY7e2Y1i2C-vphy3tmiOunO6RmxGHmGwNJco.txt"
url = "1M22mtskeY7e2Y1i2C-vphy3tmiOunO6RmxGHmGwNJco"
title = "Twilight Mirage 57: The Siege of the Lineage Brighton Pt. 1"

[[input.files]]
path = "1KJb-6ZxWvXFzCjHFt1VBXWODD_heNPw7vbstlBMA8N0.txt"
url = "1KJb-6ZxWvXFzCjHFt1VBXWODD_heNPw7vbstlBMA8N0"
title = "Twilight Mirage 58: The Siege of the Lineage Brighton Pt. 2"

[[input.files]]
path = "1GZ1Dss0Wz7xBMKlEG5IC7LPhJFcGj6KRIJ82WQiLBco.txt"
url = "1GZ1Dss0Wz7xBMKlEG5IC7LPhJFcGj6KRIJ82WQiLBco"
title = "Twilight Mirage 59: The Siege of the Lineage Brighton Pt. 3"

[[input.files]]
path = "12n2sQb_xn5NyRo0tMKjyYpj7SiEpuQoONtxZWWm61Q8.txt"
url = "12n2sQb_xn5NyRo0tMKjyYpj7SiEpuQoONtxZWWm61Q8"
title = "Twilight Mirage 60: The Restitution of All Things Pt. 1"

[[input.files]]
path = "1oirhNpv3yZIOS0EX4FIDHsVOi2Xw_l0UvNJGWDp1sz8.txt"
url = "1oirhNpv3yZIOS0EX4FIDHsVOi2Xw_l0UvNJGWDp1sz8"
title = "Twilight Mirage 61: The Restitution of All Things Pt. 2"

[[input.files]]
path = "1uLQDhnxA3RGaymJ2wuiRpEEsd2GkUtQWETKCP_plD9U.txt"
url = "1uLQDhnxA3RGaymJ2wuiRpEEsd2GkUtQWETKCP_plD9U"
title = "Twilight Mirage 62: The Feast of Patina"

[[input.files]]
path = "1trrjDujyI1ObqHJwPIU4a2oAjbx4j7i3cSPTeOf-QQc.txt"
url = "1trrjDujyI1ObqHJwPIU4a2oAjbx4j7i3cSPTeOf-QQc"
title = "Twilight Mirage 63: Guaranteed Events, Or: An Accounting of the Time When We Built the Machine"

[[input.files]]
path = "1yO2efCJUhJaOpuPnx2j2Z67c5fMwMAkFJot_8OWAaHA.txt"
url = "1yO2efCJUhJaOpuPnx2j2Z67c5fMwMAkFJot_8OWAaHA"
title = "Twilight Mirage 64: Futura Free Pt. 1"

[[input.files]]
path = "1ljy5LhbCaLsI9JyW2V0v8UwY4ids5F_tQMOHL6eMS2E.txt"
url = "1ljy5LhbCaLsI9JyW2V0v8UwY4ids5F_tQMOHL6eMS2E"
title = "Twilight Mirage 65: Futura Free Pt. 2"

[[input.files]]
path = "1ssy8Sgq1DMEawThkuaawmhg7n16LpWAfp4lSHllYMYM.txt"
url = "1ssy8Sgq1DMEawThkuaawmhg7n16LpWAfp4lSHllYMYM"
title = "Twilight Mirage 66: Futura Free Pt. 3"

[[input.files]]
path = "1g3YDsQe-cNcEB9MgX9dzBpM2E-BtqPi2Bh_3tGg48Z4.txt"
url = "1g3YDsQe-cNcEB9MgX9dzBpM2E-BtqPi2Bh_3tGg48Z4"
title = "Twilight Mirage 67: Futura Free Pt. 4"

[[input.files]]
path = "16PrXvOObbm6D-buKCXpaux5kqQa4DDNvssxgmxhyesc.txt"
url = "16PrXvOObbm6D-buKCXpaux5kqQa4DDNvssxgmxhyesc"
title = "Twilight Mirage 68: The Twilight Mirage Post Mortem"

