[input]
base_directory = "transcripts/winter-in-hieron"
url_prefix = "https://docs.google.com/document/d/"
stemming = "None"
[[input.files]]
path = "1TtgXIZ1xzrgV0m5BNbWgVWysfn36dJJPyniDalWhBm4.txt"
url = "1TtgXIZ1xzrgV0m5BNbWgVWysfn36dJJPyniDalWhBm4"
title = "Hieron: The Months of Autumn Pt 1"

[[input.files]]
path = "1_V5lKB6cazOIXf08ZoevybaeZXLhTWTiWyqx-4FAQ00.txt"
url = "1_V5lKB6cazOIXf08ZoevybaeZXLhTWTiWyqx-4FAQ00"
title = "Hieron: The Months of Autumn Pt 2"

[[input.files]]
path = "14-LucHUuVd1NU7XbjZnke4nnU-ON-2UmXjVH3Riem6o.txt"
url = "14-LucHUuVd1NU7XbjZnke4nnU-ON-2UmXjVH3Riem6o"
title = "Winter in Hieron 01: An Arrow Let Loose"

[[input.files]]
path = "1EZKv57hcZmgUrW1IvhikuCdDbLe1WCrsMPYW5lJVfw0.txt"
url = "1EZKv57hcZmgUrW1IvhikuCdDbLe1WCrsMPYW5lJVfw0"
title = "Winter in Hieron 02: A Museum in the Distance"

[[input.files]]
path = "1kTNV38eb1-Karz7FW7F9SaJlK6_tpjOLSTThC_lcNs0.txt"
url = "1kTNV38eb1-Karz7FW7F9SaJlK6_tpjOLSTThC_lcNs0"
title = "Winter in Hieron 03: You Haven’t Kept Up, Have You?"

[[input.files]]
path = "1avSyyze0bkLQ-ZY237fkdG362rjo0WUghVl2h0ieP_U.txt"
url = "1avSyyze0bkLQ-ZY237fkdG362rjo0WUghVl2h0ieP_U"
title = "Winter in Hieron 04: A Combination of Notes"

[[input.files]]
path = "1_snTsq37Yaosyi0PieAAYUnISXinW25bH0u7t2hyAgs.txt"
url = "1_snTsq37Yaosyi0PieAAYUnISXinW25bH0u7t2hyAgs"
title = "Winter in Hieron 05: Blood Doesn’t Run"

[[input.files]]
path = "1ggW6dhmbCUlWTjocnZXeJaN0bMoywAzA3Tc0tCy_-5s.txt"
url = "1ggW6dhmbCUlWTjocnZXeJaN0bMoywAzA3Tc0tCy_-5s"
title = "Winter in Hieron 06: All Violence, All Brains"

[[input.files]]
path = "1VbyARuQZXK36bnvCbRAz7FyQzud7mEWE07V21PRsAno.txt"
url = "1VbyARuQZXK36bnvCbRAz7FyQzud7mEWE07V21PRsAno"
title = "Winter in Hieron: Holiday Special 01: Homes and Promises"

[[input.files]]
path = "1Vww82yf6ED_8I1pzBqIo7IZ_ZkRqo9PX8fSBg-QIzzk.txt"
url = "1Vww82yf6ED_8I1pzBqIo7IZ_ZkRqo9PX8fSBg-QIzzk"
title = "Winter in Hieron: Holiday Special 02: Pits and Ladders"

[[input.files]]
path = "1QY2vCWmd35MKIHYHNtdra5UtUW_I3nY-bzxCvrrA1Bw.txt"
url = "1QY2vCWmd35MKIHYHNtdra5UtUW_I3nY-bzxCvrrA1Bw"
title = "Winter in Hieron 07: Two Hands"

[[input.files]]
path = "1HZt3DRmWU3sXZkglv7NhH43wGqEALiBxbhTbC2mMBiA.txt"
url = "1HZt3DRmWU3sXZkglv7NhH43wGqEALiBxbhTbC2mMBiA"
title = "Winter in Hieron 08: The Meeting House"

[[input.files]]
path = "1IhCWjP8OcBizCujRFYeSkvarSCWrCyTq2-1h3scMh_A.txt"
url = "1IhCWjP8OcBizCujRFYeSkvarSCWrCyTq2-1h3scMh_A"
title = "Winter in Hieron 09: Warm Assurances"

[[input.files]]
path = "17sojv27pAp-BmMF7aZwZH1wuK5FCgAlOrTu_wKlN63g.txt"
url = "17sojv27pAp-BmMF7aZwZH1wuK5FCgAlOrTu_wKlN63g"
title = "Winter in Hieron 10: Fire and Blood"

[[input.files]]
path = "1HyFk-6dmfanuISIi3Y-oVAcUjsaq7S372SDYsgwWM24.txt"
url = "1HyFk-6dmfanuISIi3Y-oVAcUjsaq7S372SDYsgwWM24"
title = "Takin’ a Snow Day"

[[input.files]]
path = "1cu5PkmzZzzGRl9-lNPW5BcHN1NIX6u4isswZ2-Odzto.txt"
url = "1cu5PkmzZzzGRl9-lNPW5BcHN1NIX6u4isswZ2-Odzto"
title = "Winter in Hieron 11: The Importance of Names"

[[input.files]]
path = "1XCV2D_fovTWog88_its_wufIwmP-GFudsI2vHQ720SM.txt"
url = "1XCV2D_fovTWog88_its_wufIwmP-GFudsI2vHQ720SM"
title = "Winter in Hieron 12: A Chaotic Cataloging"

[[input.files]]
path = "1pfPffnk6a389u78zA3cuq0-EexlK_4N5wGpnHlug7K8.txt"
url = "1pfPffnk6a389u78zA3cuq0-EexlK_4N5wGpnHlug7K8"
title = "Winter in Hieron 13: Rosemerrow, Oh My Rosemerrow"

[[input.files]]
path = "1eGGx5itbO2K6MypL_IKggH3exg86qQSS_jE_p_O2aBQ.txt"
url = "1eGGx5itbO2K6MypL_IKggH3exg86qQSS_jE_p_O2aBQ"
title = "Winter in Hieron 14: What Do You Want Here?"

[[input.files]]
path = "1aiAcR51Wq4visvVyV9Pz0FytlFfRnkKbdMSAxNXXB88.txt"
url = "1aiAcR51Wq4visvVyV9Pz0FytlFfRnkKbdMSAxNXXB88"
title = "Winter in Hieron 15: Settle Your Matters"

[[input.files]]
path = "1umKwazFzzIHzNulxmjT1cc2f_IiDBFemAo_yej45HyQ.txt"
url = "1umKwazFzzIHzNulxmjT1cc2f_IiDBFemAo_yej45HyQ"
title = "Winter in Hieron 16: Is There Anyone Else?"

[[input.files]]
path = "1ANCGerxiSn6v4k1T0PLg3cwNuMPjcf5AHDLu-5XcSzI.txt"
url = "1ANCGerxiSn6v4k1T0PLg3cwNuMPjcf5AHDLu-5XcSzI"
title = "Winter in Hieron 17: Undelivered Resignations"

[[input.files]]
path = "1iB-SBGuZ5wCVC5iEG--BFMCIZO5hQR1V7l3bhkoRCB8.txt"
url = "1iB-SBGuZ5wCVC5iEG--BFMCIZO5hQR1V7l3bhkoRCB8"
title = "Winter in Hieron 18: Try to Live Normally"

[[input.files]]
path = "1rCJ8OQ1atSO23_iEOvU1R2j9YAkVT41CodJpqMMlc-g.txt"
url = "1rCJ8OQ1atSO23_iEOvU1R2j9YAkVT41CodJpqMMlc-g"
title = "Winter in Hieron 19: Make The Spring Last Forever"

[[input.files]]
path = "1uIObGIs8zbaMIy8kYmjuHMLHZpqua3XxZu1A2mwY7bE.txt"
url = "1uIObGIs8zbaMIy8kYmjuHMLHZpqua3XxZu1A2mwY7bE"
title = "Winter in Hieron 20: Pulling You Further Down"

[[input.files]]
path = "1W1M9p_c-lcvtgg8TeKiIJUMez1UepP5yXZiz_l3Zyrg.txt"
url = "1W1M9p_c-lcvtgg8TeKiIJUMez1UepP5yXZiz_l3Zyrg"
title = "Winter in Hieron 21: The Shield of Our Will"

[[input.files]]
path = "1zYTlyZUxnQZv2s6Obdnn92_JXyoKzdJIes9MpYAC9Kk.txt"
url = "1zYTlyZUxnQZv2s6Obdnn92_JXyoKzdJIes9MpYAC9Kk"
title = "Winter in Hieron 22: A Holy Place"

[[input.files]]
path = "1RBXGpN2VOEXx-gKN7Vf6--zATRkhkQ6pkIRBX1LNaRY.txt"
url = "1RBXGpN2VOEXx-gKN7Vf6--zATRkhkQ6pkIRBX1LNaRY"
title = "Winter in Hieron 23: Make the Library Smile"

[[input.files]]
path = "1BY6FWPqBamQh4SozBm8HnOOpMjyQs4gUnu-qvWVjXpE.txt"
url = "1BY6FWPqBamQh4SozBm8HnOOpMjyQs4gUnu-qvWVjXpE"
title = "Winter in Hieron 24: An Open Mind"

[[input.files]]
path = "1LNMAGsThH5QPFZWBq4zMjyN3OY41zIzhONTfpvPjrIY.txt"
url = "1LNMAGsThH5QPFZWBq4zMjyN3OY41zIzhONTfpvPjrIY"
title = "Winter in Hieron 25: Twenty Two Brown Birds"

[[input.files]]
path = "1zIF4KGGJnMAffG7LQygtv9c_H08zsN8d3-CDXLPyh-s.txt"
url = "1zIF4KGGJnMAffG7LQygtv9c_H08zsN8d3-CDXLPyh-s"
title = "Winter in Hieron 26: A Shattering Note"

[[input.files]]
path = "1mExDKgviCbBJoZFnuV06NR5PouFjQp_3cPKlLRMp2OM.txt"
url = "1mExDKgviCbBJoZFnuV06NR5PouFjQp_3cPKlLRMp2OM"
title = "Winter in Hieron 27: A Good Metaphor"

[[input.files]]
path = "1wBmC8Gg4pzpaqaHvj03WlrsRDovlqGxMtv2fqru2iOY.txt"
url = "1wBmC8Gg4pzpaqaHvj03WlrsRDovlqGxMtv2fqru2iOY"
title = "Winter in Hieron 28: What Life Looks Like"

[[input.files]]
path = "1ih9POVwqoRqpWKSNBpAnGvQh7wjP9fKfgW-OYtKkMU0.txt"
url = "1ih9POVwqoRqpWKSNBpAnGvQh7wjP9fKfgW-OYtKkMU0"
title = "Winter in Hieron 29: Slow Justice"

[[input.files]]
path = "1-g0YFWU08vEbp2O1q4SC-Qsi_g5DKQwlaxr9DqbHj3A.txt"
url = "1-g0YFWU08vEbp2O1q4SC-Qsi_g5DKQwlaxr9DqbHj3A"
title = "Twilight Mirage and Patreon Announcement!"

[[input.files]]
path = "10a5kH5BbSFsxldgGK6YPT_-21H5-UUouBMNlHPXjUGU.txt"
url = "10a5kH5BbSFsxldgGK6YPT_-21H5-UUouBMNlHPXjUGU"
title = "Winter in Hieron & Marielda Post Mortem"

